[package]
name = "orx-meta-macros"
version = "1.0.0"
edition = "2024"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-meta/"
description = "Procedural macros for orx-meta"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.3"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
